version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      # Sẽ báo lỗi nếu biến môi trường không được cung cấp
      - HOST=${HOST:?HOST is not set}
      - PORT=${PORT:?PORT is not set}
      - DB_PASSWORD=${DB_PASSWORD:?DB_PASSWORD is not set}
      - DB_USER=${DB_USER:?DB_USER is not set}
      - DB_CONNECT_STRING=${DB_CONNECT_STRING:?DB_CONNECT_STRING is not set}
      - JWT_SECRET=${JWT_SECRET:?JWT_SECRET is not set}
      - DB_CHECK_STRING=${DB_CHECK_STRING:?DB_CHECK_STRING is not set}
      - DBS401_FLAG2=${DBS401_FLAG2:?DBS401_FLAG2 is not set}
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - node_modules:/app/node_modules
    depends_on:
      oracle-db:
        condition: service_healthy
    restart: unless-stopped
    command: npm run start

  oracle-db:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      - ORACLE_PWD=${ORACLE_ADMIN_PASSWORD:?ORACLE_ADMIN_PASSWORD is not set}
      - ORACLE_CHARACTERSET=AL32UTF8
    volumes:
      - ./init-scripts:/opt/oracle/scripts/setup
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "sqlplus", "-L", "system/${ORACLE_ADMIN_PASSWORD}@//localhost:1521/XEPDB1", "AS", "SYSDBA", "<<< 'SELECT 1 FROM DUAL;'" ]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 40s

volumes:
  node_modules:
  oracle-data: