version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - DB_PASSWORD=dbs401f0rEasy
      - DB_USER=dbs401
      # Important: use the service name instead of localhost
      - DB_CONNECT_STRING=oracle-db:1521/XEPDB1
      - JWT_SECRET=dbs401_10_diem_khong_nhung
    depends_on:
      - oracle-db
    restart: unless-stopped

  oracle-db:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      - ORACLE_PWD=kienpt2003
      - ORACLE_CHARACTERSET=AL32UTF8
    volumes:
      - oracle-data:/opt/oracle/oradata
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "sqlplus", "-L", "system/kienpt2003@//localhost:1521/XEPDB1", "AS", "SYSDBA", "<<< 'SELECT 1 FROM DUAL;'" ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  oracle-data:
