version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    environment:
      - HOST=${HOST}
      - PORT=${PORT}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USER=${DB_USER}
      - DB_CONNECT_STRING=${DB_CONNECT_STRING}
      - JWT_SECRET=${JWT_SECRET}
      - DB_CHECK_STRING=${DB_CHECK_STRING}
      - DBS401_FLAG2=${DBS401_FLAG2}
    volumes:
      # Mount source code directory to container
      - ./src:/app/src
      # Mount public assets
      - ./public:/app/public
    depends_on:
      oracle-db:
        condition: service_healthy
    restart: "no"
    command: >
      sh -c "npm install && npm run start"

  oracle-db:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      - ORACLE_PWD=${ORACLE_PWD}
      - ORACLE_CHARACTERSET=${ORACLE_CHARACTERSET}
    volumes:
      - ./init-scripts:/opt/oracle/scripts/setup
    # Don't use persistent storage, so database resets on each restart
    # - oracle-data:/opt/oracle/oradata
    restart: "no"
    healthcheck:
      test: [ "CMD", "sqlplus", "-L", "system/${ORACLE_PWD}@//localhost:1521/XEPDB1", "AS", "SYSDBA", "<<< 'SELECT 1 FROM DUAL;'" ]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 40s

volumes:
  # Keep this definition for compatibility even if we're not using it
  oracle-data: