-- Create table users for login and authentication
create table users (
   user_id       number
      generated by default as identity
   primary key,
   username      varchar2(50) not null unique,
   password_hash varchar2(255) not null,
   email         varchar2(100) not null unique,
   created_at    date default sysdate,
   updated_at    date
);

-- Create table user_profiles for storing user profile information
create table user_profiles (
   profile_id   number
      generated by default as identity
   primary key,
   user_id      number not null,
   full_name    varchar2(100),
   address      varchar2(255),
   phone_number varchar2(20),
   hobbies      varchar2(255),
   avatar_url   varchar2(255),
   birthday     date,
   gender       varchar2(10),
   constraint fk_user_profile_user foreign key ( user_id )
      references users ( user_id )
         on delete cascade
);

-- Push message when done
EXECUTE DBMS_OUTPUT.PUT_LINE('Script đơn giản hóa tạo bảng ACCOUNTS và USER_PROFILES đã hoàn tất!');

-- Make craft data for 2 tables:
-- INSERT INTO USERS (USERNAME, PASSWORD_HASH, EMAIL, CREATED_AT)
insert into users (
   username,
   password_hash,
   email,
   created_at
) values ( 'alice',
           'hashpass1',
           'alice@example.com',
           sysdate - 10 );
insert into users (
   username,
   password_hash,
   email,
   created_at
) values ( 'bob',
           'hashpass2',
           'bob@example.com',
           sysdate - 9 );
insert into users (
   username,
   password_hash,
   email,
   created_at
) values ( 'charlie',
           'hashpass3',
           'charlie@example.com',
           sysdate - 8 );
insert into users (
   username,
   password_hash,
   email,
   created_at
) values ( 'david',
           'hashpass4',
           'david@example.com',
           sysdate - 7 );
insert into users (
   username,
   password_hash,
   email,
   created_at
) values ( 'eva',
           'hashpass5',
           'eva@example.com',
           sysdate - 6 );
insert into users (
   username,
   password_hash,
   email,
   created_at
) values ( 'frank',
           'hashpass6',
           'frank@example.com',
           sysdate - 5 );
insert into users (
   username,
   password_hash,
   email,
   created_at
) values ( 'grace',
           'hashpass7',
           'grace@example.com',
           sysdate - 4 );
insert into users (
   username,
   password_hash,
   email,
   created_at
) values ( 'helen',
           'hashpass8',
           'helen@example.com',
           sysdate - 3 );
insert into users (
   username,
   password_hash,
   email,
   created_at
) values ( 'ian',
           'hashpass9',
           'ian@example.com',
           sysdate - 2 );
insert into users (
   username,
   password_hash,
   email,
   created_at
) values ( 'julia',
           'hashpass10',
           'julia@example.com',
           sysdate - 1 );

-- INSERT INTO USER_PROFILES (USER_ID, FULL_NAME, ADDRESS, PHONE_NUMBER, HOBBIES, AVATAR_URL, BIRTHDAY, GENDER)
insert into user_profiles (
   user_id,
   full_name,
   address,
   phone_number,
   hobbies,
   avatar_url,
   birthday,
   gender
) values ( 1,
           'Alice Nguyen',
           '123 Main St, Hanoi',
           '0901234567',
           'Reading, Painting',
           null,
           to_date('1995-01-01','YYYY-MM-DD'),
           'Female' );
insert into user_profiles (
   user_id,
   full_name,
   address,
   phone_number,
   hobbies,
   avatar_url,
   birthday,
   gender
) values ( 2,
           'Bob Tran',
           '456 Le Loi, HCMC',
           '0912345678',
           'Football, Music',
           null,
           to_date('1992-05-15','YYYY-MM-DD'),
           'Male' );
insert into user_profiles (
   user_id,
   full_name,
   address,
   phone_number,
   hobbies,
   avatar_url,
   birthday,
   gender
) values ( 3,
           'Charlie Pham',
           '789 Nguyen Trai, Danang',
           '0987654321',
           'Travel, Coding',
           null,
           to_date('1998-03-21','YYYY-MM-DD'),
           'Male' );
insert into user_profiles (
   user_id,
   full_name,
   address,
   phone_number,
   hobbies,
   avatar_url,
   birthday,
   gender
) values ( 4,
           'David Do',
           '321 Bach Mai, Hanoi',
           '0908765432',
           'Gaming, Cooking',
           null,
           to_date('1990-11-30','YYYY-MM-DD'),
           'Male' );
insert into user_profiles (
   user_id,
   full_name,
   address,
   phone_number,
   hobbies,
   avatar_url,
   birthday,
   gender
) values ( 5,
           'Eva Le',
           '654 Tran Hung Dao, Hue',
           '0976543210',
           'Dancing, Yoga',
           null,
           to_date('1997-07-17','YYYY-MM-DD'),
           'Female' );
insert into user_profiles (
   user_id,
   full_name,
   address,
   phone_number,
   hobbies,
   avatar_url,
   birthday,
   gender
) values ( 6,
           'Frank Vo',
           '147 Nguyen Hue, HCMC',
           '0956789123',
           'Swimming, Reading',
           null,
           to_date('1993-09-05','YYYY-MM-DD'),
           'Male' );
insert into user_profiles (
   user_id,
   full_name,
   address,
   phone_number,
   hobbies,
   avatar_url,
   birthday,
   gender
) values ( 7,
           'Grace Bui',
           '258 Phan Dinh Phung, Hanoi',
           '0934567891',
           'Photography, Writing',
           null,
           to_date('1996-12-09','YYYY-MM-DD'),
           'Female' );
insert into user_profiles (
   user_id,
   full_name,
   address,
   phone_number,
   hobbies,
   avatar_url,
   birthday,
   gender
) values ( 8,
           'Helen Mai',
           '369 Hai Ba Trung, HCMC',
           '0923456789',
           'Music, Baking',
           null,
           to_date('1994-04-22','YYYY-MM-DD'),
           'Female' );
insert into user_profiles (
   user_id,
   full_name,
   address,
   phone_number,
   hobbies,
   avatar_url,
   birthday,
   gender
) values ( 9,
           'Ian Nguyen',
           '159 Vo Thi Sau, Danang',
           '0919876543',
           'Cycling, Fishing',
           null,
           to_date('1991-10-02','YYYY-MM-DD'),
           'Male' );
insert into user_profiles (
   user_id,
   full_name,
   address,
   phone_number,
   hobbies,
   avatar_url,
   birthday,
   gender
) values ( 10,
           'Julia Hoang',
           '753 Tran Phu, Hue',
           '0902345678',
           'Running, Chess',
           null,
           to_date('1999-08-13','YYYY-MM-DD'),
           'Female' );

exit;